service: image-tagging-filter

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  tag:
    handler: handler.tag
    role: arn:aws:iam::316649820111:role/lambda-sqs-rekognition
    events:
      - sns: arn:aws:sns:us-east-1:316649820111:s3-nanoservices-imagens-put-topic
      