service: http-handler

plugins:
 - serverless-apigw-binary 
 - serverless-offline

custom:
  apigwBinary:
    types:           
      - 'image/jpeg'      

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  upload:
    handler: handler.upload
    role: arn:aws:iam::316649820111:role/lambda-http-handler
    events:
      - http:
          path: images
          method: post
  get:
    handler: handler.get
    role: arn:aws:iam::316649820111:role/lambda-http-handler-get
    vpc:
      subnetIds:
        - subnet-0c1f8185f15e36162        
      securityGroupIds:
        - sg-0b0351526d19be6ea
    events:
      - http:
          path: images
          method: get
